订单模块+课程模块
mozhenghong/online_mall pull request #8
Opened 2022-06-11 15:04 UTC by mozhenghong

2022-06-15 10:38 UTC, bowen-wu requested changes

2022-06-15 10:38 UTC, bowen-wu commented on src/api/order.ts
> +export interface CourseItem {
和 src/api/course.ts 中的 CourseItem 重复

2022-06-15 10:38 UTC, bowen-wu commented on src/api/order.ts
> +export interface OrderItem {
id createdOn 公共属性可否创建一个基类

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/components/addCourse/index.tsx
>    onSuccess: (isSuccess: number) => void;
isSuccess 根据名字判断应该是 boolean 类型，但是确实 number 类型，字段命名是否可以更合理

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/components/addCourse/index.tsx
>    onChangeVisible: (visible: boolean) => void;
字段命名是否合理？

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/components/addCourse/index.tsx
> +  const { visible, isEdit=false, currentId=0, onSuccess, onChangeVisible } = props;
format

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/detail/index.tsx
> +  const { courseStore, orderStore } = store;
store 只用过一次，简写

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/detail/index.tsx
> +  const [visible, setVisible] = useState(false);
字段命名

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/detail/index.tsx
> +      setDetail(res)
分号一会有，一会没有

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/detail/index.tsx
> +        <div className="course-management-detail-title" >
space

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/detail/index.tsx
> +            <Button style={{ marginRight: 20 }} onClick={() => { setCurrentId(detail.id); setIsEdit(true); setVisible(true); }} type="primary">更新课程</Button>
这 onClick 写一行？

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/detail/index.tsx
> +              <Button type="primary" style={{ marginRight: 20 }} >删除</Button>
space

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/index.scss
> +    &-item {
format

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/index.scss
> +      align-items: flex-start;
可否尝试使用 mixin

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/index.tsx
>    const { placeOrder } = orderStore;
简化

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/index.tsx
>    const [successFlag, setSuccessFlag] = useState(1);
flag 类型是 number ？

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/index.tsx
>    const getTableList = async (data: object) => {
字段语义化

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/index.tsx
>    const onFinish = (values: object) => {
能否确认类型？

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/videoDetail/index.scss
> +    $width: 1216px;
多处使用 1216 ，定义变量

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/courseManagement/videoDetail/index.tsx
> +            setDetail(res.data)
分号

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/orderManagement/detail/index.tsx
> +        setDetail(data)
分号

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/orderManagement/index.tsx
> +export const status: { [index: string]: string } = {
index??

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/orderManagement/index.tsx
> +    'PAID': '已支付'
status 可以写个枚举

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/orderManagement/index.tsx
> +            render: (text: string) => <span>{Number(text) / 100}</span>
2位小数

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/orderManagement/index.tsx
> +                    onClick={() => {
创建方法

2022-06-15 10:38 UTC, bowen-wu commented on src/pages/userManagement/components/updateUser/index.tsx
> +      getRoleList()
分号

2022-06-16 02:54 UTC, mozhenghong commented on src/pages/orderManagement/index.tsx
> +    'PAID': '已支付'
我觉得这样取值的时候方便  所以先不改

2022-06-16 02:54 UTC, mozhenghong commented on src/pages/orderManagement/index.tsx
> +    'PAID': '已支付'
哈哈哈

2022-06-16 05:47 UTC, bowen-wu requested changes

2022-06-16 05:47 UTC, bowen-wu commented on src/pages/userManagement/components/updateUser/index.tsx
>        })
分号

2022-06-16 06:49 UTC, bowen-wu requested changes

2022-06-16 06:49 UTC, bowen-wu commented on src/index.scss
> +@mixin flex($justifyContent: flex-start, $alignContent: center, $flexDirection: row) {
这个mixin在全局文件中有，只需要在你使用的地方引入就好，不用新建

2022-06-16 06:49 UTC, bowen-wu commented on src/pages/courseManagement/detail/index.tsx
空行

2022-06-16 06:49 UTC, bowen-wu commented on src/pages/courseManagement/detail/index.tsx
> +              onClick={() => {
不能定义一个方法吗？

2022-06-16 06:49 UTC, bowen-wu commented on src/pages/courseManagement/detail/index.tsx
>                placeOrder(detail.id).then(({ data }: { data: placeOrderResult }) => {
不能定义一个方法吗？

2022-06-16 06:53 UTC, mozhenghong commented on src/index.scss
> +@mixin flex($justifyContent: flex-start, $alignContent: center, $flexDirection: row) {
我又不知道你写了哼

2022-06-16 07:06 UTC, bowen-wu approved these changes

2022-06-16 07:06 UTC, merged