Feature/optimize
mozhenghong/online_mall pull request #9
Opened 2022-06-19 09:39 UTC by mozhenghong

2022-06-21 01:45 UTC, bowen-wu requested changes

2022-06-21 01:45 UTC, bowen-wu commented on src/layouts/header/index.tsx
> +  const [addCoursevisible, setAddCourseVisible] = useState(false);
addCourseVisible

2022-06-21 01:45 UTC, bowen-wu commented on src/layouts/header/index.tsx
> +interface Iprops {
IProps

2022-06-21 01:45 UTC, bowen-wu commented on src/layouts/header/index.tsx
> +            {menuList.map((item) => (
这个 menuList 应该根据角色的不同而不同吧。目前这样如果是 teacher 会有一个空余的 div 吧

2022-06-21 01:45 UTC, bowen-wu commented on src/layouts/header/index.tsx
> +                  : userName)}
这个应该可以简化吧

2022-06-21 01:45 UTC, bowen-wu commented on src/layouts/header/index.tsx
> +                  {/* <span className="item">{item.title}</span> */}
删除注释

2022-06-21 01:45 UTC, bowen-wu commented on src/pages/courseManagement/components/addCourse/index.tsx
>    const handleAdd = (values: any) => {
delete any

2022-06-21 01:45 UTC, bowen-wu commented on src/pages/courseManagement/components/addCourse/index.tsx
>    const handleUpdate = (values: any) => {
delete any

2022-06-21 01:45 UTC, bowen-wu commented on src/pages/courseManagement/detail/index.tsx
>      deleteCourse(detail.id).then(res => {
res is defined but never used

2022-06-21 01:45 UTC, bowen-wu commented on src/pages/courseManagement/detail/index.tsx
> +            <div className="course-management-detail-video-item" onClick={() => window.open(`/videoPlay?courseId=${id}&videoId=${item.id}`, '_blank')}>
没有 key

2022-06-21 01:45 UTC, bowen-wu commented on src/pages/courseManagement/detail/index.tsx
>                {' '}
这是啥？

2022-06-21 01:45 UTC, bowen-wu commented on src/pages/courseManagement/detail/index.tsx
> +            getCourseDetailMethod()
为啥要用箭头函数？

2022-06-21 01:45 UTC, bowen-wu commented on src/pages/errorPage/403.tsx
> +      {/* <Button
代码不是金子

2022-06-21 01:45 UTC, bowen-wu commented on src/pages/errorPage/404.tsx
> +      {/* <Button
代码不是金子

2022-06-21 02:11 UTC, mozhenghong commented on src/layouts/header/index.tsx
> +            {menuList.map((item) => (
menuList有role ，因为一个人可能有好几个角色

2022-06-21 09:41 UTC, bowen-wu requested changes

2022-06-21 09:41 UTC, bowen-wu commented on src/layouts/header/index.tsx
> +              {userName.length > 3 ? userName.substring(userName.length - 4) : userName}
userName 一定存在？取后4位是否可以简化？

2022-06-22 02:44 UTC, bowen-wu approved these changes

2022-06-22 02:45 UTC, merged